group: 'next_hour-mcc'
task: 'next'
head_type: 'next'

features_list: 
- hour_diff
- mcc_category

scheduler: True
num_epochs: 15
optimizer: 'adamw'
lr: 0.0001
batch_size: 4
weight_decay: 0.00001
embedding_dropout: 0.1
loss_freq: 200